# rust-toolchain.toml
[toolchain]
channel = "1.87.0"
targets = [ "x86_64-unknown-linux-gnu", "wasm32-unknown-unknown" ]
profile = "minimal"



# volitelné doplňky (přidej, pokud je potřebuješ)
# components = ["rustfmt", "clippy"]