name: Offline CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Unpack toolchain and cache
        run: |
          ./offline.sh join-toolchain
      - name: Run offline tests
        run: |
          ./offline.sh ci-setup

