name: Offline CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Unpack toolchain and cache
        run: |
          ./join_toolchain.sh
      - name: Run offline tests
        run: |
          ./ci_offline_setup.sh
